Add VIIRS SCF processing capability and merge with current IMS_proc
NOAA-PSL/land-IMS_proc pull request #7
Opened 2024-08-05 18:44 UTC by yuanxue2870

## Describe your changes  
Summarise all code changes included in PR: 
1.added VIIRS processing unit;
2.merged VIIRS processing unit with IMS processing one;
3.added VIIRS super-ob percentage threshold as a parameter in the namelist file;
4.added a new VIIRS test case, and separated from previous IMS test cases.

List any associated PRs  in the submodules.
This is the PR for the submodule land-SCF_proc.

## Issue ticket number and link
List the git Issue that this PR addresses: 
https://github.com/NOAA-PSL/land-SCF_proc/issues/6

## Test output 
Is this PR expected to pass the DA_IMS_test (ie., does it change the output)? 
Yes.

Does it pass the DA_IMS_test? 
Yes, it passed the IMS processing test case for both .nc and .ascii formatted.

If changes to the test results are expected, what are these changes? Provide a link to the output directory when running the test: 
The new benchmark output for VIIRS can be found on Hera at: /scratch2/NCEPDEV/stmp1/Yuan.Xue/pull_request/land-SCF_proc/test/VIIRSscf.20160501.C384.mx025_oro_data.nc

## Checklist before requesting a review
- [x] My branch being merged is up to date with the latest develop. 
- [x] I have performed a self-review of my code by examining the differences that will be merged.
- [x] I have not made any unnecessary code changes / changed any default behavior.
- [x] My code passes the DA_IMS_test, or differences can be explained.

2024-08-05 18:45 UTC, yuanxue2870 commented
Please review: @ClaraDraper-NOAA, @YoulongXia-NOAA, @tsga

Thank you!

2024-08-06 15:03 UTC, YoulongXia-NOAA requested changes

2024-08-06 15:03 UTC, YoulongXia-NOAA commented on CMakeLists.txt
> +./sorc/aggregate_mod.f90
aggrgate_mode.f90 => SCFaggregate_mod.F90

2024-08-06 15:03 UTC, YoulongXia-NOAA commented on README.md
IMS' => IMS

2024-08-06 15:03 UTC, YoulongXia-NOAA commented on build.sh
> +        env_file="env_GDASApp"
# cmake build script for IMS processing code  => IMS(VIIRS)
# uses GDASApp environment for consistency with workflow(s) 

Are the comments are correct after Rocky8 was update??

# only actually needs intel, impi, and netcdf
# eg: intel/2020.2 impi/2018.0.4 netcdf/4.7.0

2024-08-06 15:03 UTC, YoulongXia-NOAA commented on sorc/Makefile
> +	$(FC)  $(FFLAGS) -c driver_fSCF.f90
Add SCF before aggregate to indicate that this is for scf calculation??

2024-08-06 15:03 UTC, YoulongXia-NOAA commented on test/submit_viirs_job.sh
> +RESTART_DIR=/scratch2/NCEPDEV/stmp1/Yuan.Xue/pull_request/restart_files/
The best way do not link your personal directory. Please consult with Clara to put them in land/DA/IMS or VIRRS  directory.

2024-08-06 15:03 UTC, YoulongXia-NOAA commented on sorc/driver_fSCF.f90
> +
Although you used the same fscf.nml, but actually you put different contents. To make an identification,  how to about still using fims.nml and fviirs.nml. Here namelist  you can use two namelists. Although there  are some redundancy, but it is clear. See If Clara has different opinion

2024-08-06 15:16 UTC, yuanxue2870 commented on sorc/driver_fSCF.f90
> +
Thanks for your comments. Per discussions with Clara in June, it is more preferred having only ONE namelist for both cases. Hence, I merged fims.nml and fviirs.nml as fSCF.nml. Hence, I will leave it as fSCF.nml.

2024-08-06 15:19 UTC, yuanxue2870 commented on test/submit_viirs_job.sh
> +RESTART_DIR=/scratch2/NCEPDEV/stmp1/Yuan.Xue/pull_request/restart_files/
This is for the test case restart files. For IMS, Clara linked to her own directory. For VIIRS, for now, I put them in my own stmp directory. Later, we can put these restart files for both test cases together.

2024-08-06 15:22 UTC, YoulongXia-NOAA commented on sorc/driver_fSCF.f90
> +
If you do so, you should use single submit job including all input into single nml file. Otherwise, it is confusing the users.

2024-08-06 15:24 UTC, YoulongXia-NOAA commented on sorc/driver_fSCF.f90
> +
This is the reason you can consult with Clara. If it pushes to github, it should not use your personal directory based on my work  experience with Mike for land-data-utils.

2024-08-08 16:15 UTC, yuanxue2870 commented on CMakeLists.txt
> +./sorc/aggregate_mod.f90
Done - confirmed with Clara on 08/08/2024. Now edited as suggested. Thanks!

2024-08-08 16:15 UTC, yuanxue2870 commented on sorc/Makefile
> +	$(FC)  $(FFLAGS) -c driver_fSCF.f90
Done.

2024-08-08 16:15 UTC, yuanxue2870 commented on sorc/driver_fSCF.f90
> +
Leave the namelist as is for now per discussions with Clara on 08/08/2024.

2024-08-08 16:15 UTC, yuanxue2870 commented on README.md
Done.

2024-08-08 16:15 UTC, yuanxue2870 commented on build.sh
> +        env_file="env_GDASApp"
Done.

2024-12-20 18:37 UTC, closed without merging